version: "3.9"
services:
  db:
    image: postgres:13.2-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    volumes: 
      - tmp-postgres:/var/lib/postgresql/data
volumes: 
  tmp-postgres: