version: "3.9"
services:
  app:
    build: ./frontend
    image: tmp-frontend
    stdin_open: true
    tty: true
    ports: 
      - "3001:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/
    depends_on:
      - "server"
  server:
    build: ./backend
    image: tmp-backend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports: 
      - "8000:8000"
    volumes: 
      - ./backend/:/app/backend/
    depends_on:
      - "db"
  db:
    image: postgres:13.2-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter
    ports:
      - "5433:5433"
    volumes: 
      - twitter-welcome:/var/lib/postgresql/data
volumes: 
  twitter-welcome: